name: Prod Deploy - ECR

on:
  push:
    branches:
      - master

env:
  IAM_ROLE: ${{ secrets.IAM_ROLE_ECR }}
  AWS_REGION : "us-east-1"

# permission can be added at job level or workflow level    
permissions:
      id-token: write
      contents: read    # This is required for actions/checkout

jobs:
  build_image:
    name: Deploy Docker Image to ECR
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v2
      if: github.ref == 'refs/heads/master'

    - name: configure aws credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        role-to-assume: ${{ env.IAM_ROLE }}            # use full arn
        role-session-name: nba-elt-mlflow-cicd
        aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1
      if: github.ref == 'refs/heads/master'

    - name: Build, tag, and push image to Amazon ECR
      if: github.ref == 'refs/heads/master'
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        ECR_REPOSITORY: jacobs_repo
        IMAGE_TAG: nba_elt_ml
      run: |
        docker-compose -f docker/docker-compose.yml build
        docker push $ECR_REGISTRY/$ECR_REPOSITORY:$IMAGE_TAG