name: Prod Test - PR

on:
  pull_request:

jobs:
  pytest_build:
    name: Run Pytest 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install Python 3
        uses: actions/setup-python@v1
        with:
          python-version: 3.8
      - name: Create and populate log file
        run: |
          mkdir logs
          cat > logs/example.log
        shell: bash
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pandas==1.4.1 pytest==7.0.1 scikit-learn==1.0.2
      - name: Run tests with pytest
        run: pytest -v